Repository jenkins-x-apps/jx-app-jacoco, pull requests merged in 2019-02, with the labels that each got.

#54 Formatting README
  README.md
Labels: size/M

#52 Added initial content to readme.md.
  README.md
Labels: approved, size/L

#61 chore: adding hferentschik to OWNERS list
  OWNERS
Labels: size/M

#64 docs: Added CONTRIBUTING guide and integrated into README
  .gitignore
  CONTRIBUTING.md
  Dockerfile
  Makefile
  README.md
Labels: approved, size/M

#66 refactor: restructure source layout
  Jenkinsfile
  Makefile
  cmd/jacoco/main.go
  internal/model.go
  jacoco_analyzer_install.sh
  jacoco_analyzer_uninstall.sh
  jacoco_analyzer_upgrade.sh
  jacoco_maven_publish.sh
  jacoco_maven_run.sh
  scripts/curlloop.sh
  scripts/jenkins-x-extension-definitions.yaml
  scripts/updatebot.sh
  scripts/watch.sh
  updatebot.sh
Labels: approved, size/S

#71 docs: no need for specifying empty namespace when adding app
  README.md
Labels: size/XS

#67 refactor: using multi-stage build to retrieve certificates
  Dockerfile
  Makefile
  skaffold.yaml
Labels: approved, size/S

#73 fix: building and pushing Docker image prior Helm release
  Jenkinsfile
Labels: approved, size/S

#76 docs: adding Apache 2.0 license
  LICENSE
Labels: approved

#84 fix: cleaning up make targets and ensuring all work
  Jenkinsfile
  Makefile
Labels: approved, size/L

#81 docs: using stash command over collect to better express workflow
  README.md
Labels: approved, size/XS

#86 fix: introducing logrus logger
  Makefile
  cmd/jacoco/main.go
  go.mod
  go.sum
  internal/util/util.go
Labels: approved, size/M

#90 fix: moving .updatebot.yml into scripts directory
  scripts/.updatebot.yml
Labels: approved, size/XS

#79 Release to jenkins-x-versions at end of pipeline
  Jenkinsfile
Labels: approved, size/XS

#93 fix: moving jx step create version to the right place
  Jenkinsfile
  scripts/.updatebot.yml
  scripts/jenkins-x-extension-definitions.yaml
  scripts/updatebot.sh
Labels: approved, size/M

#78 Add a default app.yaml
  charts/jx-app-jacoco/templates/app.yaml
Labels: approved, size/XS

#94 docs: documenting testing of dev changes in cluster
  Jenkinsfile
  README.md
Labels: approved, size/S

#97 fix: adding additional permissions to role.yml
  charts/jx-app-jacoco/templates/role.yaml
Labels: approved, size/XS

#91 fix: retrying CRD retrieval and update with exponential backoff
  cmd/jacoco/main.go
  go.mod
  internal/cluster/watch.go
  internal/cluster/watch_test.go
  internal/util/util.go
  internal/util/util_test.go
Labels: approved, size/L

#96 fix: introducing top level done channel and ability to shutdown cleanly
  cmd/jacoco/main.go
  internal/cluster/watch.go
Labels: approved, size/M

#102 fix: making sure updatePipelineActivity as whole is retried
  cmd/jacoco/main.go
  internal/cluster/watch.go
  internal/cluster/watch_test.go
Labels: approved, size/L

#98 fix: updating NOTES.txt in helm charts
  .gitignore
  README.md
  charts/jx-app-jacoco/Chart.yaml
  charts/jx-app-jacoco/README.md
  charts/jx-app-jacoco/templates/NOTES.txt
Labels: approved, lgtm, size/M

#100 fix: adjusted generated Fact to use count measurement type and added …
  .dockerignore
  .helmignore
  .stignore
  internal/cluster/watch.go
  internal/cluster/watch_test.go
Labels: approved, size/M
